eval:
    gt_folder: data/results/gt
    pred_folder: data/results/predicted
    out_dir: data/results/analysis
    plots: true
    map_pretrained_counts: false
    run_yolo_eval: false
    yolo_mode: custom
    model_path: models/yolov8n_v2/weights/best.pt
    data_yaml: data/data.yaml
    device: cpu
    conf: 0.25        
    iou: 0.6
    split: val
train:
    model: "yolov8n.pt"
    data_yaml: "data/data.yaml"
    epochs: 100
    imgsz: 960
    batch: 16
    workers: 8
    device: "cpu"  # options: "cpu", "gpu", "0"
    patience: 15
    project: "models"
    name: "yolov8s"
    plots: true
    save: true
    cos_lr: true
prediction:
    paths:
        video_folder: "../data/videos/"
        output_folder: "../data/output/"
        results_folder: "../data/results/predicted/"
        model_path: "models/yolov8n_v2/weights/best.pt"
        video_filename: "vid18.mp4"
    parameters:
        confidence_threshold: 0.35
        iou_threshold: 0.35
        grey_zone_size: 20.0
        device: "cpu"
        mode: "custom"  # options: "pretrained", "custom"

