# Model registry
models:

  # =================
  # TUNED MODELS
  # =================

  # -----------------
  # YOLO tuned
  # -----------------
  yolo_tuned/yolov8s_v13:
    backend: yolo
    variant: tuned
    weights: models/yolo/v1/yolov8s_v13/weights/best.pt
    mapping: 
      tourist: 0
      skier: 1
      cyclist: 2
      tourist_dog: 3

  yolo_tuned/yolov8m_v12:
    backend: yolo
    variant: tuned
    weights: models/yolo/v1/yolov8m_v12/weights/best.pt
    mapping: 
      tourist: 0
      skier: 1
      cyclist: 2
      tourist_dog: 3

  yolo_tuned/yolo11m_v11:
    backend: yolo
    variant: tuned
    weights: models/yolo/v1/yolo11m_v11/weights/best.pt
    mapping: 
      tourist: 0
      skier: 1
      cyclist: 2
      tourist_dog: 3

  yolo_tuned/yolo11l_v11:
    backend: yolo
    variant: tuned
    weights: models/yolo/v1/yolo11l_v11/weights/best.pt
    mapping: 
      tourist: 0
      skier: 1
      cyclist: 2
      tourist_dog: 3

  yolo_tuned/yolo26s_v11:
    backend: yolo
    variant: tuned
    weights: models/yolo/v1/yolo26s_v11/weights/best.pt
    mapping: 
      tourist: 0
      skier: 1
      cyclist: 2
      tourist_dog: 3

  yolo_tuned/yolo26l_v11:
    backend: yolo
    variant: tuned
    weights: models/yolo/v1/yolo26l_v11/weights/best.pt
    mapping: 
      tourist: 0
      skier: 1
      cyclist: 2
      tourist_dog: 3

  yolo_tuned/yolo26x_v11:
    backend: yolo
    variant: tuned
    weights: models/yolo/v1/yolo26x_v11/weights/best.pt
    mapping: 
      tourist: 0
      skier: 1
      cyclist: 2
      tourist_dog: 3


  yolo_tuned/yolov8n_v2:
    backend: yolo
    variant: tuned
    weights: models\yolo\v0\yolov8n_v2\weights\best.pt
    mapping: 
      tourist: 0
      skier: 1
      cyclist: 2
      tourist_dog: 3


  # -----------------
  # RF-DETR tuned (local checkpoints)
  # -----------------
  rfdetr_tuned/rfdetr_small_v6:
    backend: rfdetr
    variant: tuned
    rfdetr_size: small
    weights: models/rfdetr/v1/rfdetr_small_v6/checkpoint_best_ema.pth
    mapping: 
      tourist: 0
      skier: 1
      cyclist: 2
      tourist_dog: 3

  rfdetr_tuned/rfdetr_medium_v2:
    backend: rfdetr
    variant: tuned
    rfdetr_size: medium
    weights: models/rfdetr/v1/rfdetr_medium_v2/checkpoint_best_ema.pth
    mapping: 
      tourist: 0
      skier: 1
      cyclist: 2
      tourist_dog: 3

  rfdetr_tuned/rfdetr_large_v3:
    backend: rfdetr
    variant: tuned
    rfdetr_size: large
    weights: models/rfdetr/v1/rfdetr_large_v3/checkpoint_best_ema.pth
    mapping: 
      tourist: 0
      skier: 1
      cyclist: 2
      tourist_dog: 3

  # =================
  # PRETRAINED MODELS
  # =================

  # -----------------
  # YOLO pretrained (COCO)
  # -----------------

  yolo_pretrained/yolov5n:
    backend: yolo
    variant: pretrained
    weights: yolov5n.pt
    mapping: 
      tourist: 0
      cyclist: 1
      tourist_dog: 16
      skier: 30

  yolo_pretrained/yolov5s:
    backend: yolo
    variant: pretrained
    weights: yolov5s.pt
    mapping: 
      tourist: 0
      cyclist: 1
      tourist_dog: 16
      skier: 30

  yolo_pretrained/yolov5m:
    backend: yolo
    variant: pretrained
    weights: yolov5m.pt
    mapping: 
      tourist: 0
      cyclist: 1
      tourist_dog: 16
      skier: 30

  yolo_pretrained/yolov5l:
    backend: yolo
    variant: pretrained
    weights: yolov5l.pt 
    mapping: 
      tourist: 0
      cyclist: 1
      tourist_dog: 16
      skier: 30

  yolo_pretrained/yolov5x:
    backend: yolo
    variant: pretrained
    weights: yolov5x.pt
    mapping: 
      tourist: 0
      cyclist: 1
      tourist_dog: 16
      skier: 30


  yolo_pretrained/yolov8n:
    backend: yolo
    variant: pretrained
    weights: yolov8n.pt
    mapping: 
      tourist: 0
      cyclist: 1
      tourist_dog: 16
      skier: 30

  yolo_pretrained/yolov8s:
    backend: yolo
    variant: pretrained
    weights: yolov8s.pt
    mapping: 
      tourist: 0
      cyclist: 1
      tourist_dog: 16
      skier: 30

  yolo_pretrained/yolov8m:
    backend: yolo
    variant: pretrained
    weights: yolov8m.pt
    mapping: 
      tourist: 0
      cyclist: 1
      tourist_dog: 16
      skier: 30

  yolo_pretrained/yolov8l:
    backend: yolo
    variant: pretrained
    weights: yolov8l.pt
    mapping: 
      tourist: 0
      cyclist: 1
      tourist_dog: 16
      skier: 30

  yolo_pretrained/yolov8x:
    backend: yolo
    variant: pretrained
    weights: yolov8x.pt
    mapping: 
      tourist: 0
      cyclist: 1
      tourist_dog: 16
      skier: 30

  yolo_prtrained/yolo11n:
    backend: yolo
    variant: pretrained
    weights: yolo11n.pt
    mapping: 
      tourist: 0
      cyclist: 1
      tourist_dog: 16
      skier: 30

  yolo_pretrained/yolo11s:
    backend: yolo
    variant: pretrained
    weights: yolo11s.pt
    mapping: 
      tourist: 0
      cyclist: 1
      tourist_dog: 16
      skier: 30

  yolo_pretrained/yolo11m:
    backend: yolo
    variant: pretrained
    weights: yolo11m.pt
    mapping: 
      tourist: 0
      cyclist: 1
      tourist_dog: 16
      skier: 30

  yolo_pretrained/yolo11l:
    backend: yolo
    variant: pretrained
    weights: yolo11l.pt
    mapping: 
      tourist: 0
      cyclist: 1
      tourist_dog: 16
      skier: 30

  yolo_pretrained/yolo11x:
    backend: yolo
    variant: pretrained
    weights: yolo11x.pt
    mapping: 
      tourist: 0
      cyclist: 1
      tourist_dog: 16
      skier: 30

  # -----------------
  # RF-DETR pretrained
  # -----------------

  rfdetr_pretrained/nano:
    backend: rfdetr
    variant: pretrained
    rfdetr_size: nano
    mapping: 
      tourist: 1
      cyclist: 2
      tourist_dog: 18
      skier: 35

  rfdetr_pretrained/small:
    backend: rfdetr
    variant: pretrained
    rfdetr_size: small
    mapping: 
      tourist: 1
      cyclist: 2
      tourist_dog: 18
      skier: 35

  rfdetr_pretrained/medium:
    backend: rfdetr
    variant: pretrained
    rfdetr_size: medium
    mapping:
      tourist: 1
      cyclist: 2
      tourist_dog: 18
      skier: 35

  rfdetr_pretrained/large:
    backend: rfdetr
    variant: pretrained
    rfdetr_size: large
    mapping:
      tourist: 1
      cyclist: 2
      tourist_dog: 18
      skier: 35

  rfdetr_pretrained/xlarge:
    backend: rfdetr
    variant: pretrained
    rfdetr_size: xlarge
    mapping:
      tourist: 1
      cyclist: 2
      tourist_dog: 18
      skier: 35

